### ISSUE TITLE
Web pages are not responsive for smaller screens

### ISSUE THREAD

**Issue by mohitgadhavi1** [YAKSHITH027/permissible-cloth-4922#73]
the overflow property might be hidden , so on smaller then desktop screens hides data if component width is more then screen width.

**Comment by mohitgadhavi1** [comment]
@YAKSHITH027  can you assign this issue to me?

**Comment by YAKSHITH027** [comment]
actually I am studying in Masai school so there I was given a team to build this project and am not supposed include any other people. so sorry I won't be able to allow.

**Comment by mohitgadhavi1** [comment]
@YAKSHITH027 No problem, thanks for responding.
